---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: database
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local

