apiVersion: v1
kind: ConfigMap
metadata:
  name: rocketmq-config
  namespace: middlerware
data:
  broker-a-slave.properties: |
    brokerClusterName=rocketmq-cluster
    brokerName=broker-a
    brokerId=1
    namesrvAddr=rocketmq.middlerware.svc.cluster.local:9876
    defaultTopicQueueNums=4
    autoCreateTopicEnable=true
    autoCreateSubscriptionGroup=true
    listenPort=20911
    deleteWhen=04
    fileReservedTime=120
    mapedFileSizeCommitLog=1073741824
    mapedFileSizeConsumeQueue=300000
    diskMaxUsedSpaceRatio=88
    storePathRootDir=/data/rocketmq/store
    maxMessageSize=65536
    brokerRole=SLAVE
    flushDiskType=SYNC_FLUSH
    brokerIP1=192.168.47.155
    listenPort=30912
  broker-a-master.properties: |
    brokerClusterName=rocketmq-cluster
    brokerName=broker-a
    brokerId=0
    namesrvAddr=rocketmq.middlerware.svc.cluster.local:9876
    defaultTopicQueueNums=4
    autoCreateTopicEnable=true
    autoCreateSubscriptionGroup=true
    listenPort=20911
    deleteWhen=04
    fileReservedTime=120
    mapedFileSizeCommitLog=1073741824
    mapedFileSizeConsumeQueue=300000
    diskMaxUsedSpaceRatio=88
    storePathRootDir=/data/rocketmq/store
    maxMessageSize=65536
    brokerRole=MASTER
    brokerIP1=192.168.47.154
    listenPort=30911    
  broker-b-slave.properties: |
    brokerClusterName=rocketmq-cluster
    brokerName=broker-b
    brokerId=1
    namesrvAddr=rocketmq.middlerware.svc.cluster.local:9876
    defaultTopicQueueNums=4
    autoCreateTopicEnable=true
    autoCreateSubscriptionGroup=true
    listenPort=20911
    deleteWhen=04
    fileReservedTime=120
    mapedFileSizeCommitLog=1073741824
    mapedFileSizeConsumeQueue=300000
    diskMaxUsedSpaceRatio=88
    storePathRootDir=/data/rocketmq/store
    maxMessageSize=65536
    brokerRole=SLAVE
    flushDiskType=SYNC_FLUSH
    brokerIP1=192.168.47.156
    listenPort=30913    
  broker-b-master.properties: |
    brokerClusterName=rocketmq-cluster
    brokerName=broker-b
    brokerId=0
    namesrvAddr=rocketmq.middlerware.svc.cluster.local:9876
    defaultTopicQueueNums=4
    autoCreateTopicEnable=true
    autoCreateSubscriptionGroup=true
    listenPort=20911
    deleteWhen=04
    fileReservedTime=120
    mapedFileSizeCommitLog=1073741824
    mapedFileSizeConsumeQueue=300000
    diskMaxUsedSpaceRatio=88
    storePathRootDir=/data/rocketmq/store
    maxMessageSize=65536
    brokerRole=MASTER
    flushDiskType=SYNC_FLUSH
    brokerIP1=192.168.47.154
    listenPort=30914